# based on https://tailscale.com/kb/1282/docker#code-examples
name: test-tailscale

services:
  tailscale:
    image: tailscale/tailscale:latest
    environment:
      TS_AUTHKEY: REPLACEME
      TS_USERSPACE: "false"
      TS_EXTRA_ARGS: "--login-server=https://tailscale.pandawork.com --reset --accept-routes=false --accept-dns"
      TS_STATE_DIR: /var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    privileged: true
